// frontend-react/src/components/Layout/List.js
import React, { Component } from 'react'
import {Link} from 'react-router-dom';
import axios from 'axios'

export default class List extends Component {

    constructor(props) {
        super(props)
        this.state = {items:[]}
    }

    componentDidMount() {
        axios.get('http://localhost/tony/backend/public/api/1.0/'+this.props.type+'?q=' + encodeURIComponent(this.props.query))
            .then(response => {
                console.log('GET RESULT', response.data);
                const items = response.data;
                items.forEach(item => {
                    item.url = this.props.detail+item.id
                })
                this.setState({items:items})
            })
            .catch(error => {
                console.log(error);
            });
    }

    render() {
        const rows = this.state.items.map(item =>
            this.props.body(item)
        )

        return (
            <div className={'col-sm-'+this.props.cols}>
                <div className="card">
                    <div className="card-header">
                        <strong>{this.props.label}</strong>
                    </div>
                    <div className="card-block">
                        <div className="row">
                            <slot name="header"></slot>
                        </div>
                        {rows}
                    </div>
                    <div className="card-footer">
                        <Link to={this.props.detail + 1} className="btn btn-default pull-right">Create</Link>
                    </div>
                </div>
            </div>
        )
    }
}

// frontend/src/components/layout/list.vue
<template>
  <div :class="clazz">
    <div class="card">
      <div class="card-header">
        <strong>{{label}}</strong>
      </div>
      <div class="card-block">
        <div class="row">
          <slot name="header"></slot>
        </div>
        <div v-if="!detail" v-for="item in items" class="row">
          <slot :item="item"></slot>
        </div>
        <div v-if="detail" v-for="item in items">
          <router-link :to="item.url">
            <div  class="row">
                <slot :item="item"></slot>
            </div>
          </router-link>
        </div>
      </div>
      <div class="card-footer">
        <router-link :to="detailNew"  class="btn btn-default pull-right">
          Create
        </router-link>
      </div>
    </div>
  </div>
</template>

<script>
  import config from '@/config.js'

    export default {
        name: 'list',
        props: ['label', 'cols', 'query', 'type', 'detail', 'with'],
        computed: {
            clazz() { return 'col-sm-' + this.cols },
            detailNew() { return this.detail + 'new' }
        },
        data() {
            return {
                items: []
            }
        },
        mounted() {
            let url = config.api + '/api/1.0/'+this.type
            let sep = '?'
            if (this.query) {
                url += sep + "q="+ encodeURIComponent(this.query)
                sep = '&'
            }
            if (this.with) {
                url += sep + 'with=' + this.with
                sep = '&'
            }

            this.$http
                .get(url)
                .then(response => {
                        console.log('GET RESULT', response.body);
                        this.items = response.body;
                        this.items.forEach(item => {
                            item.url = this.detail+item.id
                        })
                    },
                    err => this.$swal( err.statusText,
                        err.body.message?err.body.message:err.body,
                        'error')

        );
        }
    }
</script>
